version: "3.8"

services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001

  todofront:
    depends_on:
     - todoback
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback

  todotests:   
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
      - FROM_PORT=3000