version: '3'

services:
  todofront:
  image: todofrontend
  depends_on:
    - todoback 
  ports:
    - 3000:3000
  environment:
    - REACT_APP_API_HOST=todoback

todoback:
  image: todobackend
  ports:
    - 3001:3001

todotests:
  image: todotests
  depends_on:
    - todofront
    - todoback  
  environment:
    - FRONT_HOST=todofront 